name: imad_flutter
description: "Add mushaf to your flutter application easily. A Quran reader library with audio playback, bookmarks, search, and more."
version: 0.0.3
homepage: https://github.com/Itqan-community/mushaf-imad-flutter
repository: https://github.com/Itqan-community/mushaf-imad-flutter

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  audio_service: ^0.18.18
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/ayah_timing/
    - assets/quran_verse_data.json
    - assets/fasel.svg
    - assets/quran-images/1/
    - assets/quran-images/2/
    - assets/quran-images/3/
    - assets/quran-images/4/
    - assets/quran-images/5/
    - assets/quran-images/6/
    - assets/quran-images/7/
    - assets/quran-images/8/
    - assets/quran-images/9/
    - assets/quran-images/10/
    - assets/quran-images/11/
    - assets/quran-images/12/
    - assets/quran-images/13/
    - assets/quran-images/14/
    - assets/quran-images/15/
    - assets/quran-images/16/
    - assets/quran-images/17/
    - assets/quran-images/18/
    - assets/quran-images/19/
    - assets/quran-images/20/
    - assets/quran-images/21/
    - assets/quran-images/22/
    - assets/quran-images/23/
    - assets/quran-images/24/
    - assets/quran-images/25/
    - assets/quran-images/26/
    - assets/quran-images/27/
    - assets/quran-images/28/
    - assets/quran-images/29/
    - assets/quran-images/30/
    - assets/quran-images/31/
    - assets/quran-images/32/
    - assets/quran-images/33/
    - assets/quran-images/34/
    - assets/quran-images/35/
    - assets/quran-images/36/
    - assets/quran-images/37/
    - assets/quran-images/38/
    - assets/quran-images/39/
    - assets/quran-images/40/
    - assets/quran-images/41/
    - assets/quran-images/42/
    - assets/quran-images/43/
    - assets/quran-images/44/
    - assets/quran-images/45/
    - assets/quran-images/46/
    - assets/quran-images/47/
    - assets/quran-images/48/
    - assets/quran-images/49/
    - assets/quran-images/50/
    - assets/quran-images/51/
    - assets/quran-images/52/
    - assets/quran-images/53/
    - assets/quran-images/54/
    - assets/quran-images/55/
    - assets/quran-images/56/
    - assets/quran-images/57/
    - assets/quran-images/58/
    - assets/quran-images/59/
    - assets/quran-images/60/
    - assets/quran-images/61/
    - assets/quran-images/62/
    - assets/quran-images/63/
    - assets/quran-images/64/
    - assets/quran-images/65/
    - assets/quran-images/66/
    - assets/quran-images/67/
    - assets/quran-images/68/
    - assets/quran-images/69/
    - assets/quran-images/70/
    - assets/quran-images/71/
    - assets/quran-images/72/
    - assets/quran-images/73/
    - assets/quran-images/74/
    - assets/quran-images/75/
    - assets/quran-images/76/
    - assets/quran-images/77/
    - assets/quran-images/78/
    - assets/quran-images/79/
    - assets/quran-images/80/
    - assets/quran-images/81/
    - assets/quran-images/82/
    - assets/quran-images/83/
    - assets/quran-images/84/
    - assets/quran-images/85/
    - assets/quran-images/86/
    - assets/quran-images/87/
    - assets/quran-images/88/
    - assets/quran-images/89/
    - assets/quran-images/90/
    - assets/quran-images/91/
    - assets/quran-images/92/
    - assets/quran-images/93/
    - assets/quran-images/94/
    - assets/quran-images/95/
    - assets/quran-images/96/
    - assets/quran-images/97/
    - assets/quran-images/98/
    - assets/quran-images/99/
    - assets/quran-images/100/
    - assets/quran-images/101/
    - assets/quran-images/102/
    - assets/quran-images/103/
    - assets/quran-images/104/
    - assets/quran-images/105/
    - assets/quran-images/106/
    - assets/quran-images/107/
    - assets/quran-images/108/
    - assets/quran-images/109/
    - assets/quran-images/110/
    - assets/quran-images/111/
    - assets/quran-images/112/
    - assets/quran-images/113/
    - assets/quran-images/114/
    - assets/quran-images/115/
    - assets/quran-images/116/
    - assets/quran-images/117/
    - assets/quran-images/118/
    - assets/quran-images/119/
    - assets/quran-images/120/
    - assets/quran-images/121/
    - assets/quran-images/122/
    - assets/quran-images/123/
    - assets/quran-images/124/
    - assets/quran-images/125/
    - assets/quran-images/126/
    - assets/quran-images/127/
    - assets/quran-images/128/
    - assets/quran-images/129/
    - assets/quran-images/130/
    - assets/quran-images/131/
    - assets/quran-images/132/
    - assets/quran-images/133/
    - assets/quran-images/134/
    - assets/quran-images/135/
    - assets/quran-images/136/
    - assets/quran-images/137/
    - assets/quran-images/138/
    - assets/quran-images/139/
    - assets/quran-images/140/
    - assets/quran-images/141/
    - assets/quran-images/142/
    - assets/quran-images/143/
    - assets/quran-images/144/
    - assets/quran-images/145/
    - assets/quran-images/146/
    - assets/quran-images/147/
    - assets/quran-images/148/
    - assets/quran-images/149/
    - assets/quran-images/150/
    - assets/quran-images/151/
    - assets/quran-images/152/
    - assets/quran-images/153/
    - assets/quran-images/154/
    - assets/quran-images/155/
    - assets/quran-images/156/
    - assets/quran-images/157/
    - assets/quran-images/158/
    - assets/quran-images/159/
    - assets/quran-images/160/
    - assets/quran-images/161/
    - assets/quran-images/162/
    - assets/quran-images/163/
    - assets/quran-images/164/
    - assets/quran-images/165/
    - assets/quran-images/166/
    - assets/quran-images/167/
    - assets/quran-images/168/
    - assets/quran-images/169/
    - assets/quran-images/170/
    - assets/quran-images/171/
    - assets/quran-images/172/
    - assets/quran-images/173/
    - assets/quran-images/174/
    - assets/quran-images/175/
    - assets/quran-images/176/
    - assets/quran-images/177/
    - assets/quran-images/178/
    - assets/quran-images/179/
    - assets/quran-images/180/
    - assets/quran-images/181/
    - assets/quran-images/182/
    - assets/quran-images/183/
    - assets/quran-images/184/
    - assets/quran-images/185/
    - assets/quran-images/186/
    - assets/quran-images/187/
    - assets/quran-images/188/
    - assets/quran-images/189/
    - assets/quran-images/190/
    - assets/quran-images/191/
    - assets/quran-images/192/
    - assets/quran-images/193/
    - assets/quran-images/194/
    - assets/quran-images/195/
    - assets/quran-images/196/
    - assets/quran-images/197/
    - assets/quran-images/198/
    - assets/quran-images/199/
    - assets/quran-images/200/
    - assets/quran-images/201/
    - assets/quran-images/202/
    - assets/quran-images/203/
    - assets/quran-images/204/
    - assets/quran-images/205/
    - assets/quran-images/206/
    - assets/quran-images/207/
    - assets/quran-images/208/
    - assets/quran-images/209/
    - assets/quran-images/210/
    - assets/quran-images/211/
    - assets/quran-images/212/
    - assets/quran-images/213/
    - assets/quran-images/214/
    - assets/quran-images/215/
    - assets/quran-images/216/
    - assets/quran-images/217/
    - assets/quran-images/218/
    - assets/quran-images/219/
    - assets/quran-images/220/
    - assets/quran-images/221/
    - assets/quran-images/222/
    - assets/quran-images/223/
    - assets/quran-images/224/
    - assets/quran-images/225/
    - assets/quran-images/226/
    - assets/quran-images/227/
    - assets/quran-images/228/
    - assets/quran-images/229/
    - assets/quran-images/230/
    - assets/quran-images/231/
    - assets/quran-images/232/
    - assets/quran-images/233/
    - assets/quran-images/234/
    - assets/quran-images/235/
    - assets/quran-images/236/
    - assets/quran-images/237/
    - assets/quran-images/238/
    - assets/quran-images/239/
    - assets/quran-images/240/
    - assets/quran-images/241/
    - assets/quran-images/242/
    - assets/quran-images/243/
    - assets/quran-images/244/
    - assets/quran-images/245/
    - assets/quran-images/246/
    - assets/quran-images/247/
    - assets/quran-images/248/
    - assets/quran-images/249/
    - assets/quran-images/250/
    - assets/quran-images/251/
    - assets/quran-images/252/
    - assets/quran-images/253/
    - assets/quran-images/254/
    - assets/quran-images/255/
    - assets/quran-images/256/
    - assets/quran-images/257/
    - assets/quran-images/258/
    - assets/quran-images/259/
    - assets/quran-images/260/
    - assets/quran-images/261/
    - assets/quran-images/262/
    - assets/quran-images/263/
    - assets/quran-images/264/
    - assets/quran-images/265/
    - assets/quran-images/266/
    - assets/quran-images/267/
    - assets/quran-images/268/
    - assets/quran-images/269/
    - assets/quran-images/270/
    - assets/quran-images/271/
    - assets/quran-images/272/
    - assets/quran-images/273/
    - assets/quran-images/274/
    - assets/quran-images/275/
    - assets/quran-images/276/
    - assets/quran-images/277/
    - assets/quran-images/278/
    - assets/quran-images/279/
    - assets/quran-images/280/
    - assets/quran-images/281/
    - assets/quran-images/282/
    - assets/quran-images/283/
    - assets/quran-images/284/
    - assets/quran-images/285/
    - assets/quran-images/286/
    - assets/quran-images/287/
    - assets/quran-images/288/
    - assets/quran-images/289/
    - assets/quran-images/290/
    - assets/quran-images/291/
    - assets/quran-images/292/
    - assets/quran-images/293/
    - assets/quran-images/294/
    - assets/quran-images/295/
    - assets/quran-images/296/
    - assets/quran-images/297/
    - assets/quran-images/298/
    - assets/quran-images/299/
    - assets/quran-images/300/
    - assets/quran-images/301/
    - assets/quran-images/302/
    - assets/quran-images/303/
    - assets/quran-images/304/
    - assets/quran-images/305/
    - assets/quran-images/306/
    - assets/quran-images/307/
    - assets/quran-images/308/
    - assets/quran-images/309/
    - assets/quran-images/310/
    - assets/quran-images/311/
    - assets/quran-images/312/
    - assets/quran-images/313/
    - assets/quran-images/314/
    - assets/quran-images/315/
    - assets/quran-images/316/
    - assets/quran-images/317/
    - assets/quran-images/318/
    - assets/quran-images/319/
    - assets/quran-images/320/
    - assets/quran-images/321/
    - assets/quran-images/322/
    - assets/quran-images/323/
    - assets/quran-images/324/
    - assets/quran-images/325/
    - assets/quran-images/326/
    - assets/quran-images/327/
    - assets/quran-images/328/
    - assets/quran-images/329/
    - assets/quran-images/330/
    - assets/quran-images/331/
    - assets/quran-images/332/
    - assets/quran-images/333/
    - assets/quran-images/334/
    - assets/quran-images/335/
    - assets/quran-images/336/
    - assets/quran-images/337/
    - assets/quran-images/338/
    - assets/quran-images/339/
    - assets/quran-images/340/
    - assets/quran-images/341/
    - assets/quran-images/342/
    - assets/quran-images/343/
    - assets/quran-images/344/
    - assets/quran-images/345/
    - assets/quran-images/346/
    - assets/quran-images/347/
    - assets/quran-images/348/
    - assets/quran-images/349/
    - assets/quran-images/350/
    - assets/quran-images/351/
    - assets/quran-images/352/
    - assets/quran-images/353/
    - assets/quran-images/354/
    - assets/quran-images/355/
    - assets/quran-images/356/
    - assets/quran-images/357/
    - assets/quran-images/358/
    - assets/quran-images/359/
    - assets/quran-images/360/
    - assets/quran-images/361/
    - assets/quran-images/362/
    - assets/quran-images/363/
    - assets/quran-images/364/
    - assets/quran-images/365/
    - assets/quran-images/366/
    - assets/quran-images/367/
    - assets/quran-images/368/
    - assets/quran-images/369/
    - assets/quran-images/370/
    - assets/quran-images/371/
    - assets/quran-images/372/
    - assets/quran-images/373/
    - assets/quran-images/374/
    - assets/quran-images/375/
    - assets/quran-images/376/
    - assets/quran-images/377/
    - assets/quran-images/378/
    - assets/quran-images/379/
    - assets/quran-images/380/
    - assets/quran-images/381/
    - assets/quran-images/382/
    - assets/quran-images/383/
    - assets/quran-images/384/
    - assets/quran-images/385/
    - assets/quran-images/386/
    - assets/quran-images/387/
    - assets/quran-images/388/
    - assets/quran-images/389/
    - assets/quran-images/390/
    - assets/quran-images/391/
    - assets/quran-images/392/
    - assets/quran-images/393/
    - assets/quran-images/394/
    - assets/quran-images/395/
    - assets/quran-images/396/
    - assets/quran-images/397/
    - assets/quran-images/398/
    - assets/quran-images/399/
    - assets/quran-images/400/
    - assets/quran-images/401/
    - assets/quran-images/402/
    - assets/quran-images/403/
    - assets/quran-images/404/
    - assets/quran-images/405/
    - assets/quran-images/406/
    - assets/quran-images/407/
    - assets/quran-images/408/
    - assets/quran-images/409/
    - assets/quran-images/410/
    - assets/quran-images/411/
    - assets/quran-images/412/
    - assets/quran-images/413/
    - assets/quran-images/414/
    - assets/quran-images/415/
    - assets/quran-images/416/
    - assets/quran-images/417/
    - assets/quran-images/418/
    - assets/quran-images/419/
    - assets/quran-images/420/
    - assets/quran-images/421/
    - assets/quran-images/422/
    - assets/quran-images/423/
    - assets/quran-images/424/
    - assets/quran-images/425/
    - assets/quran-images/426/
    - assets/quran-images/427/
    - assets/quran-images/428/
    - assets/quran-images/429/
    - assets/quran-images/430/
    - assets/quran-images/431/
    - assets/quran-images/432/
    - assets/quran-images/433/
    - assets/quran-images/434/
    - assets/quran-images/435/
    - assets/quran-images/436/
    - assets/quran-images/437/
    - assets/quran-images/438/
    - assets/quran-images/439/
    - assets/quran-images/440/
    - assets/quran-images/441/
    - assets/quran-images/442/
    - assets/quran-images/443/
    - assets/quran-images/444/
    - assets/quran-images/445/
    - assets/quran-images/446/
    - assets/quran-images/447/
    - assets/quran-images/448/
    - assets/quran-images/449/
    - assets/quran-images/450/
    - assets/quran-images/451/
    - assets/quran-images/452/
    - assets/quran-images/453/
    - assets/quran-images/454/
    - assets/quran-images/455/
    - assets/quran-images/456/
    - assets/quran-images/457/
    - assets/quran-images/458/
    - assets/quran-images/459/
    - assets/quran-images/460/
    - assets/quran-images/461/
    - assets/quran-images/462/
    - assets/quran-images/463/
    - assets/quran-images/464/
    - assets/quran-images/465/
    - assets/quran-images/466/
    - assets/quran-images/467/
    - assets/quran-images/468/
    - assets/quran-images/469/
    - assets/quran-images/470/
    - assets/quran-images/471/
    - assets/quran-images/472/
    - assets/quran-images/473/
    - assets/quran-images/474/
    - assets/quran-images/475/
    - assets/quran-images/476/
    - assets/quran-images/477/
    - assets/quran-images/478/
    - assets/quran-images/479/
    - assets/quran-images/480/
    - assets/quran-images/481/
    - assets/quran-images/482/
    - assets/quran-images/483/
    - assets/quran-images/484/
    - assets/quran-images/485/
    - assets/quran-images/486/
    - assets/quran-images/487/
    - assets/quran-images/488/
    - assets/quran-images/489/
    - assets/quran-images/490/
    - assets/quran-images/491/
    - assets/quran-images/492/
    - assets/quran-images/493/
    - assets/quran-images/494/
    - assets/quran-images/495/
    - assets/quran-images/496/
    - assets/quran-images/497/
    - assets/quran-images/498/
    - assets/quran-images/499/
    - assets/quran-images/500/
    - assets/quran-images/501/
    - assets/quran-images/502/
    - assets/quran-images/503/
    - assets/quran-images/504/
    - assets/quran-images/505/
    - assets/quran-images/506/
    - assets/quran-images/507/
    - assets/quran-images/508/
    - assets/quran-images/509/
    - assets/quran-images/510/
    - assets/quran-images/511/
    - assets/quran-images/512/
    - assets/quran-images/513/
    - assets/quran-images/514/
    - assets/quran-images/515/
    - assets/quran-images/516/
    - assets/quran-images/517/
    - assets/quran-images/518/
    - assets/quran-images/519/
    - assets/quran-images/520/
    - assets/quran-images/521/
    - assets/quran-images/522/
    - assets/quran-images/523/
    - assets/quran-images/524/
    - assets/quran-images/525/
    - assets/quran-images/526/
    - assets/quran-images/527/
    - assets/quran-images/528/
    - assets/quran-images/529/
    - assets/quran-images/530/
    - assets/quran-images/531/
    - assets/quran-images/532/
    - assets/quran-images/533/
    - assets/quran-images/534/
    - assets/quran-images/535/
    - assets/quran-images/536/
    - assets/quran-images/537/
    - assets/quran-images/538/
    - assets/quran-images/539/
    - assets/quran-images/540/
    - assets/quran-images/541/
    - assets/quran-images/542/
    - assets/quran-images/543/
    - assets/quran-images/544/
    - assets/quran-images/545/
    - assets/quran-images/546/
    - assets/quran-images/547/
    - assets/quran-images/548/
    - assets/quran-images/549/
    - assets/quran-images/550/
    - assets/quran-images/551/
    - assets/quran-images/552/
    - assets/quran-images/553/
    - assets/quran-images/554/
    - assets/quran-images/555/
    - assets/quran-images/556/
    - assets/quran-images/557/
    - assets/quran-images/558/
    - assets/quran-images/559/
    - assets/quran-images/560/
    - assets/quran-images/561/
    - assets/quran-images/562/
    - assets/quran-images/563/
    - assets/quran-images/564/
    - assets/quran-images/565/
    - assets/quran-images/566/
    - assets/quran-images/567/
    - assets/quran-images/568/
    - assets/quran-images/569/
    - assets/quran-images/570/
    - assets/quran-images/571/
    - assets/quran-images/572/
    - assets/quran-images/573/
    - assets/quran-images/574/
    - assets/quran-images/575/
    - assets/quran-images/576/
    - assets/quran-images/577/
    - assets/quran-images/578/
    - assets/quran-images/579/
    - assets/quran-images/580/
    - assets/quran-images/581/
    - assets/quran-images/582/
    - assets/quran-images/583/
    - assets/quran-images/584/
    - assets/quran-images/585/
    - assets/quran-images/586/
    - assets/quran-images/587/
    - assets/quran-images/588/
    - assets/quran-images/589/
    - assets/quran-images/590/
    - assets/quran-images/591/
    - assets/quran-images/592/
    - assets/quran-images/593/
    - assets/quran-images/594/
    - assets/quran-images/595/
    - assets/quran-images/596/
    - assets/quran-images/597/
    - assets/quran-images/598/
    - assets/quran-images/599/
    - assets/quran-images/600/
    - assets/quran-images/601/
    - assets/quran-images/602/
    - assets/quran-images/603/
    - assets/quran-images/604/

  fonts:
    - family: QuranNumbers
      fonts:
        - asset: assets/fonts/QuranNumbers.ttf
